export const data = [
    {
      id: 1,
      nombre: "Vainillla",
      descripcion: "Usado",
      precio: 50000,
      stock: 5,
    },
    {
      id: 2,
      nombre: "Campo",
      descripcion: "Nuevo",
      precio: 100000,
      stock: 3,
    },
    {
      id: 3,
      nombre: "Clásico",
      descripcion: "Nuevo",
      precio: 150000,
      stock: 10,
    },
    {
      id: 4,
      nombre: "Moderno",
      descripcion: "Nuevo",
      precio: 150000,
      stock: 2,
    },
    {
      id: 5,
      nombre: "Paris",
      descripcion: "Usado",
      precio: 80000,
      stock: 2,
    },
    {
      id: 6,
      nombre: "Monaco",
      descripcion: "Usado",
      precio: 60000,
      stock: 2,
    },
    {
      id: 7,
      nombre: "Spain",
      descripcion: "Usado",
      precio: 50000,
      stock: 2,
    },
    {
      id: 8,
      nombre: "Italia",
      descripcion: "Nuevo",
      precio: 150000,
      stock: 2,
    },
  ]